# Generated by Django 3.1.1 on 2020-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
